#!/bin/bash 
source /etc/container_environment.sh
TXINDEX=${TXINDEX:-0}
REINDEX=${REINDEX:-0}
USER=${USER:-coin}
COIN=${COIN:-mazacoin}
COINDIR=${COINDIR:-/home/coin/.${COIN}}
RPCPASSWORD=${RPCPASSWORD}
RPCPORT=${RPCPORT:-12835}
P2PPORT=${P2PPORT:-12832}

# 
sed '/reindex/d' ${COINDIR}/${COIN}.conf > new
mv new ${COINDIR}/${COIN}.conf
sed '/txindex/d' ${COINDIR}/${COIN}.conf > new
mv new ${COINDIR}/${COIN}.conf


mk_rpcpass () {
   echo "$(date +%m-%d:%Y:%H:%M) making rpcpassword"
   sed -i '/rpcpassword/d' "${COINDIR}"/${COIN}.conf 
   pass="$(apg -a0 -n1 -m64 -x64)" 
   echo "rpcpassword=${pass}" >> "${COINDIR}"/${COIN}.conf   
}

if [ "${REINDEX}" = "1" ] 
then
   echo "reindex=1" >> "${COINDIR}"/${COIN}.conf
fi
if [ "${TXINDEX}" = "1" ]
then 
   echo "txindex=1" >> "${COINDIR}"/${COIN}.conf
fi
echo "$(date +%m-%d:%Y:%H:%M) Checking to see if this is the first known start of ${COIN}coind ${COINDIR}"
rpcpwd=$(grep rpcpassword ${COINDIR}/${COIN}.conf|awk -F\= '{print $2}')
if [ !  -f "${COINDIR}"/${COIN}.conf ] 
then 
  test -d "${COINDIR}" || mkdir -pv "${COINDIR}"
  cp -av /root/${COIN}.conf "${COINDIR}"/${COIN}.conf
  mk_rpcpass
fi
if [ -z "${rpcpwd}" ] 
then
  mk_rpcpass
fi
echo "$(date +%m-%d:%Y:%H:%M) Starting ${COIN}d"
chown -R ${USER}.${USER} ${COINDIR} 
exec su - ${USER} -c "/usr/local/bin/${COIN}d" 
